name: Generate Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Contribution Graph
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Contribution Graph
        uses: peterxcli/gh-contribution-graph-action@main
        with:
          targets: "RoyLee1224"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_dir: "."
